# Site
name: "DevLogs"
title: "DevLogs"
# description: "A Developer's Notebook"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
include: ["_pages"]

# Authors
authors:
  Sankar:
    name: Sankar
    display_name: Sankar
    avatar: assets/images/sankar_avatar.jpg
    email: mavsankar@gmail.com
    twitter: https://twitter.com/mavsankar
    description: "Author of DevLogs.  Software Engineer at Microsoft, India | IIITDM Kancheepuram, Chennai."


# Plugins 
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
